### ISSUE TITLE
Read data doesn't match

### ISSUE THREAD

**Issue by niklas-arm** [ARMmbed/example-asynch-i2c#18]
The test fails with the following message:
```
Starting transfer test 
Writing DONE, event is 8
Writing DONE (slave is ready), event is 4
Read data doesn't match with written data, event is 8
**** Test done ****
```

Tested on OS X with k64f-gcc.

**Comment by 0xc0170** [comment]
I'll check what has changed and why it fails

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1084

**Comment by niklas-arm** [comment]
The data still doesn't match. I've exchanged EEPROMs for new ones, but that didn't change anything.
