### ISSUE TITLE
example-async-i2c code

### ISSUE THREAD

**Issue by bangaragirinxp** [ARMmbed/example-asynch-i2c#22]
We observe that this example is not updated for a long time. Is this example working on any platform? We are testing this example on our JN5179 platform, but we observe issues. We would like to know whether to continue debugging the our I2C code using this example.

**Comment by 0xc0170** [comment]
Hi,

there's not much to update. mbed-drivers are still at 0.11.x version (no i2c changes). It should work for frdm k64f targets, efm32 as well.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1841

**Comment by mlnx** [comment]
@bangaragirinxp 
Could you please comment what issues you are seeing with this I2C example when testing the JN5179 platform?

**Comment by bangaragirinxp** [comment]
We are still getting this problem with the I2C example in the mbed system runtime error in file C:/NXP/mbed-os/examples/example-asynch-i2c/yotta_modules/minar/source/minar.cpp, line 111: Unable to allocate CallbackNodeREG_I2
We have done quite a bit of debug on the system outlined below :
We have been working with the JN5179 I2C peripheral, interfacing to a Microchip 24AA01 I2C serial EEPROM.
http://ww1.microchip.com/downloads/en/DeviceDoc/21711J.pdf
The I2C EEPROM which is on the NXP DR1048 board can be accessed in a number of different ways – by 8-byte pages and also reading random Bytes, byte at a time.
1.	As mentioned above We are still getting this error – We still have a few printf’s in the system but only to tell us the test has started and This was a concern but removing the debug hasn’t changed the system performance.
2.	The mbed example has required some modification to get the addressing and command words correctly on the bus to fit the 24AA01 EEPROM, but debug print messages and the I2C analyser tell us that these are ok. 
The example code isn’t quite fit for the EEPROM we are trying to interface to.
The example isn’t generic enough to work with our EEPROM since the code assumes that you can write to the EEPROM using one I2C bus transaction. 
This isn’t possible with the 24AA01  EEPROM. Data must be written on 8-byte page boundaries using a page write, or written number-of-bytes at a time using the random memory access mode. These modes require an address and the data to be written
In 2 transactions – address write then data byte(s) write – The test and the I2C C++ class API don’t really support this mechanism, It considers the read write accesses of the EEPROM to be atomic. So, the example will need some modification as it isn’t possible to write more than a page of data to the EEPROM using a single start address in a transaction (8 bytes in this case – anymore and you get overlap), the same is true for the read condition.
We’ve done local modifications to get round some of this for now. But ……
We are still getting the mbed minar error @111 – looking at whats occuring over the wire we can see the contents of theFIFO getting out on the I2C and then the transaction is terminated by the error. I’m not sure what the ramifications for the rest of the system are after this point. Our (now removed) printf debug told me that we have managed to fill the 8-byte I2C TX FIFO and transmission was underway. It terminates with this error.
You can see that there are a couple of clock glitches in there and the data is corrupted in 2 places (as the analyser is is interpreting it) – we don’t get this on our HAL implementation, so that’s interesting. This trace just shows we are getting data out of the I2C, the trace above isn’t valid for the 24AA01.  The trace just shows the data being sent over the wire as the application is currently written – with a few modifications.
We’ve changed the address to be 1 byte long, rather than 2 and the address field is changed to match the EEPROM, this is enough to get ACK’s from the device – that is all.
The application needs to be modified further to break the address set and data send portions into 2 parts. This is where the Application API gets cumbersome since the API uses callbacks and event triggers which need to be specified and aren’t documented that well in the code/header files. This API/test is not a great fit for the 24AA01.
We think the mbed I2C EEPROM API needs revisiting to account for devices like the one we are using which have an architecture based  on pages where read and write operations are not a single I2C event. An API which would allow the user to specify a chain of commands which could run sequentially at the I2C level without being so tightly coupled to the application would be much more flexible and would allow mbed to be compatible with a wider ranges of devices.

Summary
========
The application requires modification to work with the 24AA01 EEPROM. There is some issue with our mbed implementation giving the minar system error

Trace:
======
![jn5179_i2c](https://cloud.githubusercontent.com/assets/14269844/12878636/2eb63ad2-ce4e-11e5-949c-75ddbdfce935.png)

**Comment by 0xc0170** [comment]
@bangaragirinxp 

> We are still getting this problem with the I2C example in the mbed system runtime error in file C:/NXP/mbed-os/examples/example-asynch-i2c/yotta_modules/minar/source/minar.cpp, line 111: Unable to allocate CallbackNodeREG_I2

This means that an app run out of heap, it can't allocate a new callback node. Is this happening with this example? Or the one you changed. How big heap is there available? How many callbacks are scheduled?

> We have been working with the JN5179 I2C peripheral, interfacing to a Microchip 24AA01 I2C serial EEPROM.
> The example code isn’t quite fit for the EEPROM we are trying to interface to.

That's true, this is an example is for 24LC256 eeprom, which has 16bit addressing. I would like to see what changes you have done. 

> In 2 transactions – address write then data byte(s) write – The test and the I2C C++ class API don’t really support this mechanism, It considers the read write accesses of the EEPROM to be atomic. So, the example will need some modification as it isn’t possible to write more than a page of data to the EEPROM using a single start address in a transaction (8 bytes in this case – anymore and you get overlap), the same is true for the read condition.

I2C API is a driver, it's not eeprom i2c driver, therefore this should be implemented on top of i2c driver API. I imagine eeprom driver being enable to do 8 or 16 bit addressing, having information about page size (cross boundaries), page write buffer, etc.

> We think the mbed I2C EEPROM API needs revisiting to account for devices like the one we are using which have an architecture based on pages where read and write operations are not a single I2C event. An API which would allow the user to specify a chain of commands which could run sequentially at the I2C level without being so tightly coupled to the application would be much more flexible and would allow mbed to be compatible with a wider ranges of devices.

As above , this is not i2c eeprom API.

> This is where the Application API gets cumbersome since the API uses callbacks and event triggers which need to be specified and aren’t documented that well in the code/header files. This API/test is not a great fit for the 24AA01.

Please provide more details. What is missing? Create an issue, to address a problem, and share it with us even here.

> We think the mbed I2C EEPROM API needs revisiting to account for devices like the one we are using which have an architecture based on pages where read and write operations are not a single I2C event.

An eeprom requires to write first an access address (=word address) for read/write (sequence - start, device address, write, word address, data - picture illustration - http://www.totalphase.com/support/article_attachments/200061736/AT24C02_Byte_Write.png), then a user buffer (=data).  One limitation of this i2c example (it's not an example limitation but more i2c driver API) is that a user needs currently to copy the access address to a buffer and send it as one chunk (i2c transfer has only write/read buffer pointers). It would be nice to do - an access address first then a buffer (either via callback mechanism which eeprom driver could use). 

What else is missing?

**Comment by MarceloSalazar** [comment]
Closing as per request.
